import React from "react";
import { ScrollView, StyleSheet, Text } from "react-native";

const styles = StyleSheet.create({
  scroller: {
    flex: 1,
  }
});

const FontList = props => {
    return(
      <ScrollView style={styles.scroller}>
        <Text style={{fontFamily: 'Academy Engraved LET'}}>{'Academy Engraved LET: ' + props.text}</Text>
        <Text style={{fontFamily: 'AcademyEngravedLetPlain'}}>{'AcademyEngravedLetPlain: ' + props.text}</Text>
        <Text style={{fontFamily: 'Al Nile'}}>{'Al Nile: ' + props.text}</Text>
        <Text style={{fontFamily: 'AlNile-Bold'}}>{'AlNile-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'American Typewriter'}}>{'American Typewriter: ' + props.text}</Text>
        <Text style={{fontFamily: 'AmericanTypewriter-Bold'}}>{'AmericanTypewriter-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AmericanTypewriter-Condensed'}}>{'AmericanTypewriter-Condensed: ' + props.text}</Text>
        <Text style={{fontFamily: 'AmericanTypewriter-CondensedBold'}}>{'AmericanTypewriter-CondensedBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AmericanTypewriter-CondensedLight'}}>{'AmericanTypewriter-CondensedLight: ' + props.text}</Text>
        <Text style={{fontFamily: 'AmericanTypewriter-Light'}}>{'AmericanTypewriter-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'Apple Color Emoji'}}>{'Apple Color Emoji: ' + props.text}</Text>
        <Text style={{fontFamily: 'Apple SD Gothic Neo'}}>{'Apple SD Gothic Neo: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleColorEmoji'}}>{'AppleColorEmoji: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleSDGothicNeo-Bold'}}>{'AppleSDGothicNeo-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleSDGothicNeo-Light'}}>{'AppleSDGothicNeo-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleSDGothicNeo-Medium'}}>{'AppleSDGothicNeo-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleSDGothicNeo-Regular'}}>{'AppleSDGothicNeo-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleSDGothicNeo-SemiBold'}}>{'AppleSDGothicNeo-SemiBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleSDGothicNeo-Thin'}}>{'AppleSDGothicNeo-Thin: ' + props.text}</Text>
        <Text style={{fontFamily: 'AppleSDGothicNeo-UltraLight'}}>{'AppleSDGothicNeo-UltraLight: ' + props.text}</Text>
        <Text style={{fontFamily: 'Arial'}}>{'Arial: ' + props.text}</Text>
        <Text style={{fontFamily: 'Arial Hebrew'}}>{'Arial Hebrew: ' + props.text}</Text>
        <Text style={{fontFamily: 'Arial Rounded MT Bold'}}>{'Arial Rounded MT Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Arial-BoldItalicMT'}}>{'Arial-BoldItalicMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'Arial-BoldMT'}}>{'Arial-BoldMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'Arial-ItalicMT'}}>{'Arial-ItalicMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'ArialHebrew'}}>{'ArialHebrew: ' + props.text}</Text>
        <Text style={{fontFamily: 'ArialHebrew-Bold'}}>{'ArialHebrew-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'ArialHebrew-Light'}}>{'ArialHebrew-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'ArialMT'}}>{'ArialMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'ArialRoundedMTBold'}}>{'ArialRoundedMTBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir'}}>{'Avenir: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir Next'}}>{'Avenir Next: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir Next Condensed'}}>{'Avenir Next Condensed: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-Black'}}>{'Avenir-Black: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-BlackOblique'}}>{'Avenir-BlackOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-Book'}}>{'Avenir-Book: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-BookOblique'}}>{'Avenir-BookOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-Heavy'}}>{'Avenir-Heavy: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-HeavyOblique'}}>{'Avenir-HeavyOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-Light'}}>{'Avenir-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-LightOblique'}}>{'Avenir-LightOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-Medium'}}>{'Avenir-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-MediumOblique'}}>{'Avenir-MediumOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-Oblique'}}>{'Avenir-Oblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Avenir-Roman'}}>{'Avenir-Roman: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-Bold'}}>{'AvenirNext-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-BoldItalic'}}>{'AvenirNext-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-DemiBold'}}>{'AvenirNext-DemiBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-DemiBoldItalic'}}>{'AvenirNext-DemiBoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-Heavy'}}>{'AvenirNext-Heavy: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-HeavyItalic'}}>{'AvenirNext-HeavyItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-Italic'}}>{'AvenirNext-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-Medium'}}>{'AvenirNext-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-MediumItalic'}}>{'AvenirNext-MediumItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-Regular'}}>{'AvenirNext-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-UltraLight'}}>{'AvenirNext-UltraLight: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNext-UltraLightItalic'}}>{'AvenirNext-UltraLightItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-Bold'}}>{'AvenirNextCondensed-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-BoldItalic'}}>{'AvenirNextCondensed-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-DemiBold'}}>{'AvenirNextCondensed-DemiBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-DemiBoldItalic'}}>{'AvenirNextCondensed-DemiBoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-Heavy'}}>{'AvenirNextCondensed-Heavy: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-HeavyItalic'}}>{'AvenirNextCondensed-HeavyItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-Italic'}}>{'AvenirNextCondensed-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-Medium'}}>{'AvenirNextCondensed-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-MediumItalic'}}>{'AvenirNextCondensed-MediumItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-Regular'}}>{'AvenirNextCondensed-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-UltraLight'}}>{'AvenirNextCondensed-UltraLight: ' + props.text}</Text>
        <Text style={{fontFamily: 'AvenirNextCondensed-UltraLightItalic'}}>{'AvenirNextCondensed-UltraLightItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Bangla Sangam MN'}}>{'Bangla Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'Baskerville'}}>{'Baskerville: ' + props.text}</Text>
        <Text style={{fontFamily: 'Baskerville-Bold'}}>{'Baskerville-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Baskerville-BoldItalic'}}>{'Baskerville-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Baskerville-Italic'}}>{'Baskerville-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Baskerville-SemiBold'}}>{'Baskerville-SemiBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Baskerville-SemiBoldItalic'}}>{'Baskerville-SemiBoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Bodoni 72'}}>{'Bodoni 72: ' + props.text}</Text>
        <Text style={{fontFamily: 'Bodoni 72 Oldstyle'}}>{'Bodoni 72 Oldstyle: ' + props.text}</Text>
        <Text style={{fontFamily: 'Bodoni 72 Smallcaps'}}>{'Bodoni 72 Smallcaps: ' + props.text}</Text>
        <Text style={{fontFamily: 'Bodoni Ornaments'}}>{'Bodoni Ornaments: ' + props.text}</Text>
        <Text style={{fontFamily: 'BodoniOrnamentsITCTT'}}>{'BodoniOrnamentsITCTT: ' + props.text}</Text>
        <Text style={{fontFamily: 'BodoniSvtyTwoITCTT-Bold'}}>{'BodoniSvtyTwoITCTT-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'BodoniSvtyTwoITCTT-Book'}}>{'BodoniSvtyTwoITCTT-Book: ' + props.text}</Text>
        <Text style={{fontFamily: 'BodoniSvtyTwoITCTT-BookIta'}}>{'BodoniSvtyTwoITCTT-BookIta: ' + props.text}</Text>
        <Text style={{fontFamily: 'BodoniSvtyTwoOSITCTT-Bold'}}>{'BodoniSvtyTwoOSITCTT-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'BodoniSvtyTwoOSITCTT-Book'}}>{'BodoniSvtyTwoOSITCTT-Book: ' + props.text}</Text>
        <Text style={{fontFamily: 'BodoniSvtyTwoSCITCTT-Book'}}>{'BodoniSvtyTwoSCITCTT-Book: ' + props.text}</Text>
        <Text style={{fontFamily: 'Bradley Hand'}}>{'Bradley Hand: ' + props.text}</Text>
        <Text style={{fontFamily: 'BradleyHandITCTT-Bold'}}>{'BradleyHandITCTT-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Chalkboard SE'}}>{'Chalkboard SE: ' + props.text}</Text>
        <Text style={{fontFamily: 'ChalkboardSE-Bold'}}>{'ChalkboardSE-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'ChalkboardSE-Light'}}>{'ChalkboardSE-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'ChalkboardSE-Regular'}}>{'ChalkboardSE-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'Chalkduster'}}>{'Chalkduster: ' + props.text}</Text>
        <Text style={{fontFamily: 'Chalkduster'}}>{'Chalkduster: ' + props.text}</Text>
        <Text style={{fontFamily: 'Cochin'}}>{'Cochin: ' + props.text}</Text>
        <Text style={{fontFamily: 'Cochin-Bold'}}>{'Cochin-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Cochin-BoldItalic'}}>{'Cochin-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Cochin-Italic'}}>{'Cochin-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Copperplate'}}>{'Copperplate: ' + props.text}</Text>
        <Text style={{fontFamily: 'Copperplate-Bold'}}>{'Copperplate-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Copperplate-Light'}}>{'Copperplate-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'Courier'}}>{'Courier: ' + props.text}</Text>
        <Text style={{fontFamily: 'Courier New'}}>{'Courier New: ' + props.text}</Text>
        <Text style={{fontFamily: 'Courier-Bold'}}>{'Courier-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Courier-BoldOblique'}}>{'Courier-BoldOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Courier-Oblique'}}>{'Courier-Oblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'CourierNewPS-BoldItalicMT'}}>{'CourierNewPS-BoldItalicMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'CourierNewPS-BoldMT'}}>{'CourierNewPS-BoldMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'CourierNewPS-ItalicMT'}}>{'CourierNewPS-ItalicMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'CourierNewPSMT'}}>{'CourierNewPSMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'Damascus'}}>{'Damascus: ' + props.text}</Text>
        <Text style={{fontFamily: 'DamascusBold'}}>{'DamascusBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'DamascusLight'}}>{'DamascusLight: ' + props.text}</Text>
        <Text style={{fontFamily: 'DamascusMedium'}}>{'DamascusMedium: ' + props.text}</Text>
        <Text style={{fontFamily: 'DamascusSemiBold'}}>{'DamascusSemiBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Devanagari Sangam MN'}}>{'Devanagari Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'DevanagariSangamMN'}}>{'DevanagariSangamMN: ' + props.text}</Text>
        <Text style={{fontFamily: 'DevanagariSangamMN-Bold'}}>{'DevanagariSangamMN-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Didot'}}>{'Didot: ' + props.text}</Text>
        <Text style={{fontFamily: 'Didot-Bold'}}>{'Didot-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Didot-Italic'}}>{'Didot-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'DiwanMishafi'}}>{'DiwanMishafi: ' + props.text}</Text>
        <Text style={{fontFamily: 'Euphemia UCAS'}}>{'Euphemia UCAS: ' + props.text}</Text>
        <Text style={{fontFamily: 'EuphemiaUCAS-Bold'}}>{'EuphemiaUCAS-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'EuphemiaUCAS-Italic'}}>{'EuphemiaUCAS-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Farah'}}>{'Farah: ' + props.text}</Text>
        <Text style={{fontFamily: 'Futura'}}>{'Futura: ' + props.text}</Text>
        <Text style={{fontFamily: 'Futura-CondensedExtraBold'}}>{'Futura-CondensedExtraBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Futura-CondensedMedium'}}>{'Futura-CondensedMedium: ' + props.text}</Text>
        <Text style={{fontFamily: 'Futura-Medium'}}>{'Futura-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'Futura-MediumItalic'}}>{'Futura-MediumItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Geeza Pro'}}>{'Geeza Pro: ' + props.text}</Text>
        <Text style={{fontFamily: 'GeezaPro-Bold'}}>{'GeezaPro-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Georgia'}}>{'Georgia: ' + props.text}</Text>
        <Text style={{fontFamily: 'Georgia-Bold'}}>{'Georgia-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Georgia-BoldItalic'}}>{'Georgia-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Georgia-Italic'}}>{'Georgia-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Gill Sans'}}>{'Gill Sans: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-Bold'}}>{'GillSans-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-BoldItalic'}}>{'GillSans-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-Italic'}}>{'GillSans-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-Light'}}>{'GillSans-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-LightItalic'}}>{'GillSans-LightItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-SemiBold'}}>{'GillSans-SemiBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-SemiBoldItalic'}}>{'GillSans-SemiBoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'GillSans-UltraBold'}}>{'GillSans-UltraBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Heiti SC'}}>{'Heiti SC: ' + props.text}</Text>
        <Text style={{fontFamily: 'Heiti TC'}}>{'Heiti TC: ' + props.text}</Text>
        <Text style={{fontFamily: 'Helvetica'}}>{'Helvetica: ' + props.text}</Text>
        <Text style={{fontFamily: 'Helvetica Neue'}}>{'Helvetica Neue: ' + props.text}</Text>
        <Text style={{fontFamily: 'Helvetica-Bold'}}>{'Helvetica-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Helvetica-BoldOblique'}}>{'Helvetica-BoldOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Helvetica-Light'}}>{'Helvetica-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'Helvetica-LightOblique'}}>{'Helvetica-LightOblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'Helvetica-Oblique'}}>{'Helvetica-Oblique: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-Bold'}}>{'HelveticaNeue-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-BoldItalic'}}>{'HelveticaNeue-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-CondensedBlack'}}>{'HelveticaNeue-CondensedBlack: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-CondensedBold'}}>{'HelveticaNeue-CondensedBold: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-Italic'}}>{'HelveticaNeue-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-Light'}}>{'HelveticaNeue-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-LightItalic'}}>{'HelveticaNeue-LightItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-Medium'}}>{'HelveticaNeue-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-MediumItalic'}}>{'HelveticaNeue-MediumItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-Thin'}}>{'HelveticaNeue-Thin: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-ThinItalic'}}>{'HelveticaNeue-ThinItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-UltraLight'}}>{'HelveticaNeue-UltraLight: ' + props.text}</Text>
        <Text style={{fontFamily: 'HelveticaNeue-UltraLightItalic'}}>{'HelveticaNeue-UltraLightItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Hiragino Mincho ProN'}}>{'Hiragino Mincho ProN: ' + props.text}</Text>
        <Text style={{fontFamily: 'Hiragino Sans'}}>{'Hiragino Sans: ' + props.text}</Text>
        <Text style={{fontFamily: 'HiraginoSans-W3'}}>{'HiraginoSans-W3: ' + props.text}</Text>
        <Text style={{fontFamily: 'HiraginoSans-W6'}}>{'HiraginoSans-W6: ' + props.text}</Text>
        <Text style={{fontFamily: 'HiraMinProN-W3'}}>{'HiraMinProN-W3: ' + props.text}</Text>
        <Text style={{fontFamily: 'HiraMinProN-W6'}}>{'HiraMinProN-W6: ' + props.text}</Text>
        <Text style={{fontFamily: 'Hoefler Text'}}>{'Hoefler Text: ' + props.text}</Text>
        <Text style={{fontFamily: 'HoeflerText-Black'}}>{'HoeflerText-Black: ' + props.text}</Text>
        <Text style={{fontFamily: 'HoeflerText-BlackItalic'}}>{'HoeflerText-BlackItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'HoeflerText-Italic'}}>{'HoeflerText-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'HoeflerText-Regular'}}>{'HoeflerText-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'Iowan Old Style'}}>{'Iowan Old Style: ' + props.text}</Text>
        <Text style={{fontFamily: 'IowanOldStyle-Bold'}}>{'IowanOldStyle-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'IowanOldStyle-BoldItalic'}}>{'IowanOldStyle-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'IowanOldStyle-Italic'}}>{'IowanOldStyle-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'IowanOldStyle-Roman'}}>{'IowanOldStyle-Roman: ' + props.text}</Text>
        <Text style={{fontFamily: 'Kailasa'}}>{'Kailasa:  ' + props.text}</Text>
        <Text style={{fontFamily: 'Kailasa-Bold'}}>{'Kailasa-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Khmer Sangam MN'}}>{'Khmer Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'Kohinoor Bangla'}}>{'Kohinoor Bangla: ' + props.text}</Text>
        <Text style={{fontFamily: 'Kohinoor Devanagari'}}>{'Kohinoor Devanagari: ' + props.text}</Text>
        <Text style={{fontFamily: 'Kohinoor Telugu'}}>{'Kohinoor Telugu: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorBangla-Light'}}>{'KohinoorBangla-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorBangla-Regular'}}>{'KohinoorBangla-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorBangla-Semibold'}}>{'KohinoorBangla-Semibold: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorDevanagari-Light'}}>{'KohinoorDevanagari-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorDevanagari-Regular'}}>{'KohinoorDevanagari-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorDevanagari-Semibold'}}>{'KohinoorDevanagari-Semibold: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorTelugu-Light'}}>{'KohinoorTelugu-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorTelugu-Medium'}}>{'KohinoorTelugu-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'KohinoorTelugu-Regular'}}>{'KohinoorTelugu-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'Lao Sangam MN'}}>{'Lao Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'Malayalam Sangam MN'}}>{'Malayalam Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'MalayalamSangamMN'}}>{'MalayalamSangamMN: ' + props.text}</Text>
        <Text style={{fontFamily: 'MalayalamSangamMN-Bold'}}>{'MalayalamSangamMN-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Marker Felt'}}>{'Marker Felt: ' + props.text}</Text>
        <Text style={{fontFamily: 'MarkerFelt-Thin'}}>{'MarkerFelt-Thin: ' + props.text}</Text>
        <Text style={{fontFamily: 'MarkerFelt-Wide'}}>{'MarkerFelt-Wide: ' + props.text}</Text>
        <Text style={{fontFamily: 'Menlo'}}>{'Menlo: ' + props.text}</Text>
        <Text style={{fontFamily: 'Menlo-Bold'}}>{'Menlo-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Menlo-BoldItalic'}}>{'Menlo-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Menlo-Italic'}}>{'Menlo-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Menlo-Regular'}}>{'Menlo-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'Mishafi'}}>{'Mishafi: ' + props.text}</Text>
        <Text style={{fontFamily: 'Noteworthy'}}>{'Noteworthy: ' + props.text}</Text>
        <Text style={{fontFamily: 'Noteworthy-Bold'}}>{'Noteworthy-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Noteworthy-Light'}}>{'Noteworthy-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'Optima'}}>{'Optima: ' + props.text}</Text>
        <Text style={{fontFamily: 'Optima-Bold'}}>{'Optima-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Optima-BoldItalic'}}>{'Optima-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Optima-ExtraBlack'}}>{'Optima-ExtraBlack: ' + props.text}</Text>
        <Text style={{fontFamily: 'Optima-Italic'}}>{'Optima-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Optima-Regular'}}>{'Optima-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'Palatino'}}>{'Palatino: ' + props.text}</Text>
        <Text style={{fontFamily: 'Palatino-Bold'}}>{'Palatino-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Palatino-BoldItalic'}}>{'Palatino-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Palatino-Italic'}}>{'Palatino-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Palatino-Roman'}}>{'Palatino-Roman: ' + props.text}</Text>
        <Text style={{fontFamily: 'Papyrus'}}>{'Papyrus: ' + props.text}</Text>
        <Text style={{fontFamily: 'Papyrus-Condensed'}}>{'Papyrus-Condensed: ' + props.text}</Text>
        <Text style={{fontFamily: 'Party LET'}}>{'Party LET: ' + props.text}</Text>
        <Text style={{fontFamily: 'PartyLetPlain'}}>{'PartyLetPlain: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFang HK'}}>{'PingFang HK: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFang SC'}}>{'PingFang SC: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFang TC'}}>{'PingFang TC: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangHK-Light'}}>{'PingFangHK-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangHK-Medium'}}>{'PingFangHK-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangHK-Regular'}}>{'PingFangHK-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangHK-Semibold'}}>{'PingFangHK-Semibold: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangHK-Thin'}}>{'PingFangHK-Thin: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangHK-Ultralight'}}>{'PingFangHK-Ultralight: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangSC-Light'}}>{'PingFangSC-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangSC-Medium'}}>{'PingFangSC-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangSC-Regular'}}>{'PingFangSC-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangSC-Semibold'}}>{'PingFangSC-Semibold: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangSC-Thin'}}>{'PingFangSC-Thin: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangSC-Ultralight'}}>{'PingFangSC-Ultralight: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangTC-Light'}}>{'PingFangTC-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangTC-Medium'}}>{'PingFangTC-Medium: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangTC-Regular'}}>{'PingFangTC-Regular: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangTC-Semibold'}}>{'PingFangTC-Semibold: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangTC-Thin'}}>{'PingFangTC-Thin: ' + props.text}</Text>
        <Text style={{fontFamily: 'PingFangTC-Ultralight'}}>{'PingFangTC-Ultralight: ' + props.text}</Text>
        <Text style={{fontFamily: 'Savoye LET'}}>{'Savoye LET: ' + props.text}</Text>
        <Text style={{fontFamily: 'SavoyeLetPlain'}}>{'SavoyeLetPlain: ' + props.text}</Text>
        <Text style={{fontFamily: 'Sinhala Sangam MN'}}>{'Sinhala Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'SinhalaSangamMN'}}>{'SinhalaSangamMN: ' + props.text}</Text>
        <Text style={{fontFamily: 'SinhalaSangamMN-Bold'}}>{'SinhalaSangamMN-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Snell Roundhand'}}>{'Snell Roundhand: ' + props.text}</Text>
        <Text style={{fontFamily: 'SnellRoundhand-Black'}}>{'SnellRoundhand-Black: ' + props.text}</Text>
        <Text style={{fontFamily: 'SnellRoundhand-Bold'}}>{'SnellRoundhand-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Symbol'}}>{'Symbol: ' + props.text}</Text>
        <Text style={{fontFamily: 'Tamil Sangam MN'}}>{'Tamil Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'TamilSangamMN-Bold'}}>{'TamilSangamMN-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Telugu Sangam MN'}}>{'Telugu Sangam MN: ' + props.text}</Text>
        <Text style={{fontFamily: 'Thonburi'}}>{'Thonburi: ' + props.text}</Text>
        <Text style={{fontFamily: 'Thonburi-Bold'}}>{'Thonburi-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Thonburi-Light'}}>{'Thonburi-Light: ' + props.text}</Text>
        <Text style={{fontFamily: 'Times New Roman'}}>{'Times New Roman: ' + props.text}</Text>
        <Text style={{fontFamily: 'TimesNewRomanPS-BoldItalicMT'}}>{'TimesNewRomanPS-BoldItalicMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'TimesNewRomanPS-BoldMT'}}>{'TimesNewRomanPS-BoldMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'TimesNewRomanPS-ItalicMT'}}>{'TimesNewRomanPS-ItalicMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'TimesNewRomanPSMT'}}>{'TimesNewRomanPSMT: ' + props.text}</Text>
        <Text style={{fontFamily: 'Trebuchet MS'}}>{'Trebuchet MS: ' + props.text}</Text>
        <Text style={{fontFamily: 'Trebuchet-BoldItalic'}}>{'Trebuchet-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'TrebuchetMS-Bold'}}>{'TrebuchetMS-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'TrebuchetMS-Italic'}}>{'TrebuchetMS-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Verdana'}}>{'Verdana: ' + props.text}</Text>
        <Text style={{fontFamily: 'Verdana-Bold'}}>{'Verdana-Bold: ' + props.text}</Text>
        <Text style={{fontFamily: 'Verdana-BoldItalic'}}>{'Verdana-BoldItalic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Verdana-Italic'}}>{'Verdana-Italic: ' + props.text}</Text>
        <Text style={{fontFamily: 'Zapf Dingbats'}}>{'Zapf Dingbats: ' + props.text}</Text>
        <Text style={{fontFamily: 'ZapfDingbatsITC'}}>{'ZapfDingbatsITC: ' + props.text}</Text>
        <Text style={{fontFamily: 'Zapfino'}}>{'Zapfino: ' + props.text}</Text>
      </ScrollView>
    );
}

export default FontList

